name: Destroy app on Airbase
on: workflow_dispatch
jobs:
  Airbase-Destroy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    container:
      image: gdssingapore/airbase:cli-n
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Airbase Login
        shell: bash
        run: |
          airbase --version
          echo "${{ secrets.AIRBASE_RC }}" > ~/.airbaserc
          airbase login --ci
      - name: Airbase Destroy
        shell: bash
        run: |
          airbase container destroy --yes abc
